/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import GestionDeQuejas.APP;
import GestionDeQuejas.Queja;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import Visual.View;
import static Visual.View.jTable1;

import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author WINDOWS
 */
public class BuscarXFecha extends javax.swing.JFrame {
 private APP app;
DefaultTableModel dtm;
private View view;
private Queja queja;
private Registro reg;
    /**
     * Creates new form BuscarXFecha
     
     */
    public BuscarXFecha(APP app) {
        dtm = (DefaultTableModel) jTable1.getModel();
        setTitle("Buscar por Fecha");
          setLocationRelativeTo(null);
        this.app=app;
       
 
        initComponents();
    }

    private BuscarXFecha() {
        
       
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
public void borrarTabla(){
          for (int j=0;j<dtm.getRowCount();j++){
               dtm.setValueAt(null,j ,0);         
           dtm.setValueAt(null,j ,1); 
          dtm.setValueAt(null,j,2);
          dtm.setValueAt(null,j,3);
            dtm.setValueAt(null,j,4);
            dtm.setValueAt(null,j,5);
              dtm.setValueAt(null,j,6);
               dtm.setValueAt(null,j,7);
               dtm.setValueAt(null,j,8);
                dtm.setValueAt(null,j,9);
                 dtm.setValueAt(null,j,10);
                  dtm.setValueAt(null,j,11);
                  dtm.setValueAt(null,j,12);
                  dtm.setValueAt(null,j,13);
                   dtm.setValueAt(null,j,14);
         }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        selection = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setForeground(new java.awt.Color(102, 0, 0));
        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jDateChooser1.setIcon(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Fecha :");
        jLabel1.setToolTipText("");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/newpackage/True Buscar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        selection.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        selection.setForeground(new java.awt.Color(0, 51, 102));
        selection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fecha Recibo", "Fecha Término", "Fecha Entrega al Dpto afectado", "Fecha Entrega de la respuesta" }));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Tipo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButton1)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String p=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
      int seleccion=selection.getSelectedIndex();
System.out.println(p);
           
        
        for (int j=0;j<dtm.getRowCount();j++){
               dtm.setValueAt(null,j ,0);         
           dtm.setValueAt(null,j ,1); 
          dtm.setValueAt(null,j,2);
          dtm.setValueAt(null,j,3);
            dtm.setValueAt(null,j,4);
            dtm.setValueAt(null,j,5);
              dtm.setValueAt(null,j,6);
               dtm.setValueAt(null,j,7);
               dtm.setValueAt(null,j,8);
                dtm.setValueAt(null,j,9);
                 dtm.setValueAt(null,j,10);
                  dtm.setValueAt(null,j,11);
                  dtm.setValueAt(null,j,12);
                  dtm.setValueAt(null,j,13);
                   dtm.setValueAt(null,j,14);
         }
        if(seleccion==0){
//       app.BuscarPorFechaR(p);
            for (int j=0;j<app.cantB();j++){
           
           
               dtm.setValueAt(app.getPos(j)+1,j ,0);         
           dtm.setValueAt(app.getBuscador(j).getNombre(),j ,1); 
          dtm.setValueAt(app.getBuscador(j).getEntAfectada(),j,2);
          dtm.setValueAt(app.getBuscador(j).getModalidad(),j,3);
            dtm.setValueAt(app.getBuscador(j).getVia(),j,4);
            dtm.setValueAt(app.getBuscador(j).getProcedencia(),j,5);
              dtm.setValueAt(app.getBuscador(j).getClasificacion(),j,6);
               dtm.setValueAt(app.getBuscador(j).getCasoPrensa(),j,7);
                dtm.setValueAt(app.getBuscador(j).getConclusion(),j,8);
                 dtm.setValueAt(app.getBuscador(j).getSatifaccion(),j,9);
                   dtm.setValueAt(app.getBuscador(j).getSatisfaccion2(),j,10);
                  dtm.setValueAt(app.getBuscador(j).getFechaR(),j,11);
                  dtm.setValueAt(app.getBuscador(j).getFechaT(),j,12);
                  dtm.setValueAt(app.getBuscador(j).getFechaDeEntregaAlDepartamentoAfectado(),j,13);
                  dtm.setValueAt(app.getBuscador(j).getFechtaDeEntregaDeLaRespuesta(),j,14);
         }
       Queja x[] = new Queja [1000];
       int q[]=new int [1000];
       app.setBuscador(x);
       app.setPos(q);
       
       }
        if(seleccion==1){
//        app.BuscarPorFechaT(p);
        for (int j=0;j<app.cantB();j++){
           
           
           
               dtm.setValueAt(app.getPos(j)+1,j ,0);         
           dtm.setValueAt(app.getBuscador(j).getNombre(),j ,1); 
          dtm.setValueAt(app.getBuscador(j).getEntAfectada(),j,2);
          dtm.setValueAt(app.getBuscador(j).getModalidad(),j,3);
            dtm.setValueAt(app.getBuscador(j).getVia(),j,4);
            dtm.setValueAt(app.getBuscador(j).getProcedencia(),j,5);
              dtm.setValueAt(app.getBuscador(j).getClasificacion(),j,6);
               dtm.setValueAt(app.getBuscador(j).getCasoPrensa(),j,7);
                dtm.setValueAt(app.getBuscador(j).getConclusion(),j,8);
                 dtm.setValueAt(app.getBuscador(j).getSatifaccion(),j,9);
                   dtm.setValueAt(app.getBuscador(j).getSatisfaccion2(),j,10);
                  dtm.setValueAt(app.getBuscador(j).getFechaR(),j,11);
                  dtm.setValueAt(app.getBuscador(j).getFechaT(),j,12);
                  dtm.setValueAt(app.getBuscador(j).getFechaDeEntregaAlDepartamentoAfectado(),j,13);
                  dtm.setValueAt(app.getBuscador(j).getFechtaDeEntregaDeLaRespuesta(),j,14);
         }
       Queja x[] = new Queja [1000];
       int q[]=new int [1000];
       app.setBuscador(x);
       app.setPos(q);
       
        }
        if(seleccion==3){
//            app.BuscarPorFechaDeEntregaAlDepartamentoAfectado(p);
                for (int j=0;j<app.cantB();j++){
           
           
           
               dtm.setValueAt(app.getPos(j)+1,j ,0);         
           dtm.setValueAt(app.getBuscador(j).getNombre(),j ,1); 
          dtm.setValueAt(app.getBuscador(j).getEntAfectada(),j,2);
          dtm.setValueAt(app.getBuscador(j).getModalidad(),j,3);
            dtm.setValueAt(app.getBuscador(j).getVia(),j,4);
            dtm.setValueAt(app.getBuscador(j).getProcedencia(),j,5);
              dtm.setValueAt(app.getBuscador(j).getClasificacion(),j,6);
               dtm.setValueAt(app.getBuscador(j).getCasoPrensa(),j,7);
                dtm.setValueAt(app.getBuscador(j).getConclusion(),j,8);
                 dtm.setValueAt(app.getBuscador(j).getSatifaccion(),j,9);
                   dtm.setValueAt(app.getBuscador(j).getSatisfaccion2(),j,10);
                  dtm.setValueAt(app.getBuscador(j).getFechaR(),j,11);
                  dtm.setValueAt(app.getBuscador(j).getFechaT(),j,12);
                  dtm.setValueAt(app.getBuscador(j).getFechaDeEntregaAlDepartamentoAfectado(),j,13);
                  dtm.setValueAt(app.getBuscador(j).getFechtaDeEntregaDeLaRespuesta(),j,14);
         }
       Queja x[] = new Queja [1000];
       int q[]=new int [1000];
       app.setBuscador(x);
       app.setPos(q);
        
        }
        if(seleccion==4){
//            app.BuscarPorFechaDeEntregaDeLaRespuesta(p);
                 for (int j=0;j<app.cantB();j++){
           
           
           
               dtm.setValueAt(app.getPos(j)+1,j ,0);         
           dtm.setValueAt(app.getBuscador(j).getNombre(),j ,1); 
          dtm.setValueAt(app.getBuscador(j).getEntAfectada(),j,2);
          dtm.setValueAt(app.getBuscador(j).getModalidad(),j,3);
            dtm.setValueAt(app.getBuscador(j).getVia(),j,4);
            dtm.setValueAt(app.getBuscador(j).getProcedencia(),j,5);
              dtm.setValueAt(app.getBuscador(j).getClasificacion(),j,6);
               dtm.setValueAt(app.getBuscador(j).getCasoPrensa(),j,7);
                dtm.setValueAt(app.getBuscador(j).getConclusion(),j,8);
                 dtm.setValueAt(app.getBuscador(j).getSatifaccion(),j,9);
                   dtm.setValueAt(app.getBuscador(j).getSatisfaccion2(),j,10);
                  dtm.setValueAt(app.getBuscador(j).getFechaR(),j,11);
                  dtm.setValueAt(app.getBuscador(j).getFechaT(),j,12);
                  dtm.setValueAt(app.getBuscador(j).getFechaDeEntregaAlDepartamentoAfectado(),j,13);
                  dtm.setValueAt(app.getBuscador(j).getFechtaDeEntregaDeLaRespuesta(),j,14);
         }
       Queja x[] = new Queja [1000];
       int q[]=new int [1000];
       app.setBuscador(x);
       app.setPos(q);
       
        }
  

      this.dispose();
       
         
  
    
    }//GEN-LAST:event_jButton1ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarXFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarXFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarXFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarXFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarXFecha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> selection;
    // End of variables declaration//GEN-END:variables
}
