/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import GestionDeQuejas.APP;
import GestionDeQuejas.Queja;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WINDOWS
 */
public class BuscarNombre extends javax.swing.JFrame {
private APP app;
DefaultTableModel dtm;
    
    /**
     * Creates new form BuscarNombre
     */
    public BuscarNombre(APP app) {
        initComponents();
          setLocationRelativeTo(null);
         this.app=app;
         setTitle("Buscar por Nombre");
        dtm = (DefaultTableModel) View.jTable1.getModel();
    }

    private BuscarNombre() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Nombre:");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/newpackage/True Buscar.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 22, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String p=jTextField1.getText();
        for (int j=0;j<dtm.getRowCount();j++){
               dtm.setValueAt(null,j ,0);         
           dtm.setValueAt(null,j ,1); 
          dtm.setValueAt(null,j,2);
          dtm.setValueAt(null,j,3);
            dtm.setValueAt(null,j,4);
            dtm.setValueAt(null,j,5);
              dtm.setValueAt(null,j,6);
               dtm.setValueAt(null,j,7);
               dtm.setValueAt(null,j,8);
                dtm.setValueAt(null,j,9);
                 dtm.setValueAt(null,j,10);
                  dtm.setValueAt(null,j,11);
                  dtm.setValueAt(null,j,12);
                  dtm.setValueAt(null,j,13);
                   dtm.setValueAt(null,j,14);
         }
//       app.BuscarPorNombre(p);
       for (int j=0;j<app.cantB();j++){
           
           
           
               dtm.setValueAt(app.getPos(j)+1,j ,0);         
           dtm.setValueAt(app.getBuscador(j).getNombre(),j ,1); 
          dtm.setValueAt(app.getBuscador(j).getEntAfectada(),j,2);
          dtm.setValueAt(app.getBuscador(j).getModalidad(),j,3);
            dtm.setValueAt(app.getBuscador(j).getVia(),j,4);
            dtm.setValueAt(app.getBuscador(j).getProcedencia(),j,5);
              dtm.setValueAt(app.getBuscador(j).getClasificacion(),j,6);
               dtm.setValueAt(app.getBuscador(j).getCasoPrensa(),j,7);
                dtm.setValueAt(app.getBuscador(j).getConclusion(),j,8);
                 dtm.setValueAt(app.getBuscador(j).getSatifaccion(),j,9);
                   dtm.setValueAt(app.getBuscador(j).getSatisfaccion2(),j,10);
                  dtm.setValueAt(app.getBuscador(j).getFechaR(),j,11);
                  dtm.setValueAt(app.getBuscador(j).getFechaT(),j,12);
                  dtm.setValueAt(app.getBuscador(j).getFechaDeEntregaAlDepartamentoAfectado(),j,13);
                  dtm.setValueAt(app.getBuscador(j).getFechtaDeEntregaDeLaRespuesta(),j,14);
         }
       Queja x[] = new Queja [1000];
       int q[]=new int [1000];
       app.setBuscador(x);
       app.setPos(q);
       
       
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarNombre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
