/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;
import GestionDeQuejas.APP;
import GestionDeQuejas.Connector;
import GestionDeQuejas.Queja;
import static Visual.View.jTable1;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author WINDOWS
 */
public class Busqueda extends javax.swing.JFrame {
private APP app;
 DefaultTableModel dtm;
  Connector enlace=new Connector ();
    Connection conect=enlace.conectar();
    private int yearss;
    /**
     * Creates new form Busqueda
     */
    public Busqueda(APP app,int years) {
        initComponents();
         setLocationRelativeTo(null);
         this.app=app;
         setTitle("Buscador");
 this.yearss=years;
         satisfaccion.setVisible(false);
        conclusa.setVisible(false);
            conclusb.setVisible(false);
            conclusc.setVisible(false);
            satisfaccion1.setVisible(false);
          dtm = (DefaultTableModel) jTable1.getModel();
        
   
          
          
       
    }

    private Busqueda() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
 public void borrarTabla(){
          for (int j=0;j<dtm.getRowCount();j++){
              dtm.setValueAt(null,j ,0);       
           dtm.setValueAt(null,j ,1); 
          dtm.setValueAt(null,j,2);
          dtm.setValueAt(null,j,3);
            dtm.setValueAt(null,j,4);
            dtm.setValueAt(null,j,5);
              dtm.setValueAt(null,j,6);
               dtm.setValueAt(null,j,7);
               dtm.setValueAt(null,j,8);
                dtm.setValueAt(null,j,9);
                 dtm.setValueAt(null,j,10);
                  dtm.setValueAt(null,j,11);
                  dtm.setValueAt(null,j,12);
                  dtm.setValueAt(null,j,13);
                   dtm.setValueAt(null,j,14);
         }
   
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        name1 = new javax.swing.JLabel();
        entidad1 = new javax.swing.JLabel();
        entidad = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        modalida = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Vias = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        procede = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        clasificacio = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        caso = new javax.swing.JComboBox<>();
        estadoE = new javax.swing.JComboBox<>();
        satisfaccion1 = new javax.swing.JLabel();
        satisfaccion = new javax.swing.JComboBox<>();
        conclusa = new javax.swing.JComboBox<>();
        conclusb = new javax.swing.JComboBox<>();
        conclusc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        dia = new com.toedter.components.JSpinField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(636, 406));
        jPanel1.setMinimumSize(new java.awt.Dimension(636, 406));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/newpackage/True Buscar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        name.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 51, 102)));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });

        name1.setBackground(new java.awt.Color(255, 255, 255));
        name1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        name1.setForeground(new java.awt.Color(0, 102, 153));
        name1.setText("Nombre y Apellidos:");

        entidad1.setBackground(new java.awt.Color(255, 255, 255));
        entidad1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        entidad1.setForeground(new java.awt.Color(0, 102, 153));
        entidad1.setText("Entidad Afectada:");

        entidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        entidad.setForeground(new java.awt.Color(102, 0, 0));
        entidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ", "1.Recursos Humanos", "2. Higiene y Epidemiología", "3. Asistencia Médica", "4. Vicedirección Económica", "5. Vicedirección General" }));
        entidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        entidad.setFocusable(false);
        entidad.setOpaque(false);
        entidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entidadActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Modalidad:");

        modalida.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        modalida.setForeground(new java.awt.Color(102, 0, 0));
        modalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "1. Solicitud", "2. Queja", "3. Anónimo o Denuncia", "4. Sugerencia", "5. Reclamaciones", "6. Reconocimientos" }));
        modalida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modalida.setFocusable(false);
        modalida.setOpaque(false);
        modalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modalidaActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Vías:");

        Vias.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Vias.setForeground(new java.awt.Color(102, 0, 0));
        Vias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "1. Carta", "2. Entrevista", "3. Teléfono" }));
        Vias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Vias.setFocusable(false);
        Vias.setOpaque(false);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Procedencia:");

        procede.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        procede.setForeground(new java.awt.Color(102, 0, 0));
        procede.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "1. MINSAP", "2. PCC", "3. APPP", "4. Directo al Sectorial", "5. Otros" }));
        procede.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        procede.setFocusable(false);
        procede.setOpaque(false);
        procede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procedeActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Clasificación:");

        clasificacio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        clasificacio.setForeground(new java.awt.Color(102, 0, 0));
        clasificacio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "1. Asistencia Médica", "2. APS y Enfermería", "3. Por fallecimiento", "4. Higiene", "5. Medicina óptica y audición", "6. Asistencia Social", "7. Docencia", "8. Laborales", "9. Problemas Administrativos", "10. Ambulancias", "11. Solicitud de RH y Materiales", "12. Construcción y Mantenimiento", "13. Trato", "14. Condiciones de trabajo", "15. Vivienda", "16. Salidas del pais ", "17. Otras", " " }));
        clasificacio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clasificacio.setFocusable(false);
        clasificacio.setMinimumSize(new java.awt.Dimension(226, 23));
        clasificacio.setOpaque(false);
        clasificacio.setPreferredSize(new java.awt.Dimension(226, 23));
        clasificacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasificacioActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Caso de prensa:");

        caso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        caso.setForeground(new java.awt.Color(102, 0, 0));
        caso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ", "No", "Plataforma Bienestar", "Periódico Granma" }));
        caso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        caso.setFocusable(false);
        caso.setMinimumSize(new java.awt.Dimension(226, 23));
        caso.setOpaque(false);
        caso.setPreferredSize(new java.awt.Dimension(226, 23));
        caso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casoActionPerformed(evt);
            }
        });

        estadoE.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        estadoE.setForeground(new java.awt.Color(102, 0, 0));
        estadoE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "Entregado", "No Entregado" }));
        estadoE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        estadoE.setFocusable(false);
        estadoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoEActionPerformed(evt);
            }
        });

        satisfaccion1.setBackground(new java.awt.Color(255, 255, 255));
        satisfaccion1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        satisfaccion1.setForeground(new java.awt.Color(0, 102, 153));
        satisfaccion1.setText("Satisfacción:");

        satisfaccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        satisfaccion.setForeground(new java.awt.Color(102, 0, 0));
        satisfaccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "Conforme", "Conforme en Parte", "Inconforme" }));
        satisfaccion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        satisfaccion.setFocusable(false);
        satisfaccion.setMaximumSize(new java.awt.Dimension(129, 23));
        satisfaccion.setMinimumSize(new java.awt.Dimension(129, 23));
        satisfaccion.setOpaque(false);
        satisfaccion.setPreferredSize(new java.awt.Dimension(129, 23));
        satisfaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satisfaccionActionPerformed(evt);
            }
        });

        conclusa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        conclusa.setForeground(new java.awt.Color(102, 0, 0));
        conclusa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ", "Con Razón", "Sin Razón", "Con Razón en Parte" }));
        conclusa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        conclusa.setFocusable(false);
        conclusa.setMaximumSize(new java.awt.Dimension(129, 23));
        conclusa.setMinimumSize(new java.awt.Dimension(129, 23));
        conclusa.setOpaque(false);
        conclusa.setPreferredSize(new java.awt.Dimension(129, 23));
        conclusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conclusaActionPerformed(evt);
            }
        });

        conclusb.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        conclusb.setForeground(new java.awt.Color(102, 0, 0));
        conclusb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "Resuelto", "En vías de solución", "Sin solución" }));
        conclusb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        conclusb.setFocusable(false);
        conclusb.setMaximumSize(new java.awt.Dimension(129, 23));
        conclusb.setMinimumSize(new java.awt.Dimension(129, 23));
        conclusb.setOpaque(false);
        conclusb.setPreferredSize(new java.awt.Dimension(129, 23));
        conclusb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conclusbActionPerformed(evt);
            }
        });

        conclusc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        conclusc.setForeground(new java.awt.Color(102, 0, 0));
        conclusc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "Con Lugar", "Con Lugar en Parte", "Sin Lugar" }));
        conclusc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        conclusc.setFocusable(false);
        conclusc.setMaximumSize(new java.awt.Dimension(129, 23));
        conclusc.setMinimumSize(new java.awt.Dimension(129, 23));
        conclusc.setOpaque(false);
        conclusc.setPreferredSize(new java.awt.Dimension(129, 23));
        conclusc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluscActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("Conclusiones:");

        Exit.setBackground(new java.awt.Color(255, 255, 255));
        Exit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(0, 0, 51));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/newpackage/Rectángulo 3.png"))); // NOI18N
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("Mes");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setText("Dia");

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 102, 153));
        jCheckBox1.setText("Quejas Atrasadas");

        jMonthChooser1.setForeground(new java.awt.Color(0, 102, 102));

        dia.setMaximum(31);
        dia.setMinimum(1);
        dia.setValue(1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(satisfaccion1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(satisfaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(conclusb, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(conclusc, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(conclusa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(entidad1)
                                    .addComponent(name1)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estadoE, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(modalida, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(name)
                                .addComponent(entidad, 0, 227, Short.MAX_VALUE)
                                .addComponent(Vias, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(procede, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clasificacio, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(caso, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jCheckBox1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name1)
                    .addComponent(satisfaccion1)
                    .addComponent(satisfaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entidad1)
                            .addComponent(entidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(modalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Vias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(procede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(clasificacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(conclusa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conclusb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conclusc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(caso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = false;
        boolean minusculas = false;
        boolean espacio = false;

        mayusculas = key >= 63 && key <= 90;
        minusculas = key >= 95 && key <= 122;
        espacio = key == 32;

        if (!(minusculas || mayusculas || espacio))
        evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyTyped

    private void entidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entidadActionPerformed

    private void modalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modalidaActionPerformed
        int item = modalida.getSelectedIndex();
        int con = estadoE.getSelectedIndex();
        if(item==0 && con==2 || item==0 && con==0 || item==0){
            conclusa.setVisible(false);
            conclusb.setVisible(false);
            conclusc.setVisible(false);
        }
        if(item==1 && con==1){
            conclusa.setVisible(false);
            conclusb.setVisible(true);
            conclusc.setVisible(false);
        }
        if(item==2&& con==1){
            conclusa.setVisible(true);
            conclusb.setVisible(false);
            conclusc.setVisible(false);
        }
        if(item==3&& con==1){
            conclusa.setVisible(false);
            conclusb.setVisible(false);
            conclusc.setVisible(true);
        }
        if(item==4&& con==2 || item==0 && con==0|| item==4){
            conclusa.setVisible(false);
            conclusb.setVisible(false);
            conclusc.setVisible(false);
        }
        if(item==5&& con==1){
            conclusa.setVisible(false);
            conclusb.setVisible(false);
            conclusc.setVisible(true);
        }
        if(item==6&& con==2 || item==0 && con==0 || item==6){
            conclusa.setVisible(false);
            conclusb.setVisible(false);
            conclusc.setVisible(false);
        }
    }//GEN-LAST:event_modalidaActionPerformed

    private void procedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procedeActionPerformed

    private void clasificacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasificacioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clasificacioActionPerformed

    private void casoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casoActionPerformed

    private void estadoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoEActionPerformed
        int item = estadoE.getSelectedIndex();
        int mod = modalida.getSelectedIndex();
        if (item==1) {
            satisfaccion.setVisible(true);
            satisfaccion1.setVisible(true);
            
        }
        if (item==2 || item==0){
            satisfaccion.setVisible(false);
            satisfaccion1.setVisible(false);
            conclusa.setVisible(false);
            conclusb.setVisible(false);
            conclusc.setVisible(false);

        }

        if(mod==0 && item==2 || mod==0 && item==0){
            conclusa.setVisible(false);
            conclusb.setVisible(false);
            conclusc.setVisible(false);
        }
        if(mod==1 && item==1){
            conclusa.setVisible(false);
            conclusb.setVisible(true);
            conclusc.setVisible(false);
        }
        if(mod==2&& item==1){
            conclusa.setVisible(true);
            conclusb.setVisible(false);
            conclusc.setVisible(false);
        }
        if(mod==3&& item==1){
            conclusa.setVisible(false);
            conclusb.setVisible(false);
            conclusc.setVisible(true);
        }
        if(mod==4&& item==2 || mod==0 && item==0){
            conclusa.setVisible(false);
            conclusb.setVisible(false);
            conclusc.setVisible(false);
        }
        if(mod==5&& item==1){
            conclusa.setVisible(false);
            conclusb.setVisible(false);
            conclusc.setVisible(true);
        }
        if(mod==6&& item==2 || mod==0 && item==0){
            conclusa.setVisible(false);
            conclusb.setVisible(false);
            conclusc.setVisible(false);
        }
     
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoEActionPerformed

    private void satisfaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satisfaccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satisfaccionActionPerformed

    private void conclusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conclusaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conclusaActionPerformed

    private void conclusbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conclusbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conclusbActionPerformed

    private void concluscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_concluscActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed

        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        String[] registros=new String[500];
     String tabla="QUEJAS";
  if (yearss==2023){
      tabla="q";
  }
  if (yearss==2024){
      tabla="qu";
  }
  if (yearss==2030){
      tabla="quejassss";
  }
  if (yearss==2025){
      tabla="que";
  }
  if (yearss==2026){
      tabla="quej";
  }
  if (yearss==2027){
      tabla="queja";
  }
  if (yearss==2028){
      tabla="quejass";
  }
  if (yearss==2029){
      tabla="quejasss";
  }
     
     
     String atrasada="No";     
     if (jCheckBox1.isSelected())
         atrasada="Si";
 
       String sql = "SELECT  *  FROM "+ tabla + 
" WHERE  CONCAT (POSICION,' ',NOMBREYAPELLIDOS, '  '  , ENTIDADAFECTADA, '  ' , MODALIDAD,' ',VIA,' ',PROCEDENCIA,' ',CLASIFICACION,' ',CASOPRENSA,' ',ESTADODEENTREGA,' ',SATISFACCION,' ',CONCLUSION)  LIKE   '%"+name.getText()+"%' "+
               " and  CONCAT (POSICION,' ',NOMBREYAPELLIDOS, '  '  , ENTIDADAFECTADA, '  ' , MODALIDAD,' ',VIA,' ',PROCEDENCIA,' ',CLASIFICACION,' ',CASOPRENSA,' ',ESTADODEENTREGA,' ',SATISFACCION,' ',CONCLUSION,' ',EMPTY)  LIKE   '%"+entidad.getSelectedItem()+"%'"+
               " and  CONCAT (POSICION,' ',NOMBREYAPELLIDOS, '  '  , ENTIDADAFECTADA, '  ' , MODALIDAD,' ',VIA,' ',PROCEDENCIA,' ',CLASIFICACION,' ',CASOPRENSA,' ',ESTADODEENTREGA,' ',SATISFACCION,' ',CONCLUSION,' ',EMPTY)  LIKE   '%"+modalida.getSelectedItem()+"%'"+
               " and  CONCAT (POSICION,' ',NOMBREYAPELLIDOS, '  '  , ENTIDADAFECTADA, '  ' , MODALIDAD,' ',VIA,' ',PROCEDENCIA,' ',CLASIFICACION,' ',CASOPRENSA,' ',ESTADODEENTREGA,' ',SATISFACCION,' ',CONCLUSION,' ',EMPTY)  LIKE   '%"+Vias.getSelectedItem()+"%'"+
               " and  CONCAT (POSICION,' ',NOMBREYAPELLIDOS, '  '  , ENTIDADAFECTADA, '  ' , MODALIDAD,' ',VIA,' ',PROCEDENCIA,' ',CLASIFICACION,' ',CASOPRENSA,' ',ESTADODEENTREGA,' ',SATISFACCION,' ',CONCLUSION,' ',EMPTY)  LIKE   '%"+procede.getSelectedItem()+"%'"+
               " and  CONCAT (POSICION,' ',NOMBREYAPELLIDOS, '  '  , ENTIDADAFECTADA, '  ' , MODALIDAD,' ',VIA,' ',PROCEDENCIA,' ',CLASIFICACION,' ',CASOPRENSA,' ',ESTADODEENTREGA,' ',SATISFACCION,' ',CONCLUSION,' ',EMPTY)  LIKE   '%"+clasificacio.getSelectedItem()+"%'"+
               " and  CONCAT (POSICION,' ',NOMBREYAPELLIDOS, '  '  , ENTIDADAFECTADA, '  ' , MODALIDAD,' ',VIA,' ',PROCEDENCIA,' ',CLASIFICACION,' ',CASOPRENSA,' ',ESTADODEENTREGA,' ',SATISFACCION,' ',CONCLUSION,' ',EMPTY)  LIKE   '%"+caso.getSelectedItem()+"%'"+
               " and  CONCAT (POSICION,' ',NOMBREYAPELLIDOS, '  '  , ENTIDADAFECTADA, '  ' , MODALIDAD,' ',VIA,' ',PROCEDENCIA,' ',CLASIFICACION,' ',CASOPRENSA,' ',ESTADODEENTREGA,' ',SATISFACCION,' ',CONCLUSION,' ',EMPTY)  LIKE   '%"+estadoE.getSelectedItem()+"%'"+
               " and  CONCAT (POSICION,' ',NOMBREYAPELLIDOS, '  '  , ENTIDADAFECTADA, '  ' , MODALIDAD,' ',VIA,' ',PROCEDENCIA,' ',CLASIFICACION,' ',CASOPRENSA,' ',ESTADODEENTREGA,' ',SATISFACCION,' ',CONCLUSION,' ',EMPTY)  LIKE   '%"+satisfaccion.getSelectedItem()+"%'"+
               " and  CONCAT (POSICION,' ',NOMBREYAPELLIDOS, '  '  , ENTIDADAFECTADA, '  ' , MODALIDAD,' ',VIA,' ',PROCEDENCIA,' ',CLASIFICACION,' ',CASOPRENSA,' ',ESTADODEENTREGA,' ',SATISFACCION,' ',CONCLUSION,' ',EMPTY)  LIKE   '%"+conclusa.getSelectedItem()+"%'"+
               " and  CONCAT (POSICION,' ',NOMBREYAPELLIDOS, '  '  , ENTIDADAFECTADA, '  ' , MODALIDAD,' ',VIA,' ',PROCEDENCIA,' ',CLASIFICACION,' ',CASOPRENSA,' ',ESTADODEENTREGA,' ',SATISFACCION,' ',CONCLUSION,' ',EMPTY)  LIKE   '%"+conclusb.getSelectedItem()+"%'"+
               " and  CONCAT (POSICION,' ',NOMBREYAPELLIDOS, '  '  , ENTIDADAFECTADA, '  ' , MODALIDAD,' ',VIA,' ',PROCEDENCIA,' ',CLASIFICACION,' ',CASOPRENSA,' ',ESTADODEENTREGA,' ',SATISFACCION,' ',CONCLUSION,' ',EMPTY)  LIKE   '%"+conclusc.getSelectedItem()+"%'"+
               " and ATRASADA = '"+atrasada+"';";
       
              
      
                      
         try {
               Statement st =(Statement) conect.createStatement();
                ResultSet rs;
             rs = st.executeQuery(sql);
      borrarTabla();
                int i=0;
                while(rs.next()){
                registros[0]=rs.getString("POSICION");
                registros[1]=rs.getString("NOMBREYAPELLIDOS");
                registros[2]=rs.getString("ENTIDADAFECTADA");
                registros[3]=rs.getString("MODALIDAD");
                registros[4]=rs.getString("VIA");
                registros[5]=rs.getString("PROCEDENCIA");
                registros[6]=rs.getString("CLASIFICACION");
                registros[7]=rs.getString("CASOPRENSA");
                registros[8]=rs.getString("ESTADODEENTREGA");
                registros[9]=rs.getString("SATISFACCION");
                registros[10]=rs.getString("CONCLUSION");
                registros[11]=rs.getString("FECHARECIVIDA");
                registros[12]=rs.getString("FECHATERMINO");
                registros[13]=rs.getString("FECHAENTREGAALDEP");
                registros[14]=rs.getString("FECHAENTREGARESPUESTA");
               
             
      View.buscar(registros, i);
      i++;
                }
            

            
               
               
                }catch (SQLException ex) {
             Logger.getLogger(Busqueda.class.getName()).log(Level.SEVERE, null, ex);
         }
                
             
            

      this.dispose();
       
      
                       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JComboBox<String> Vias;
    private javax.swing.JComboBox<String> caso;
    private javax.swing.JComboBox<String> clasificacio;
    private javax.swing.JComboBox<String> conclusa;
    private javax.swing.JComboBox<String> conclusb;
    private javax.swing.JComboBox<String> conclusc;
    private com.toedter.components.JSpinField dia;
    private javax.swing.JComboBox<String> entidad;
    private javax.swing.JLabel entidad1;
    private javax.swing.JComboBox<String> estadoE;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> modalida;
    private javax.swing.JTextField name;
    private javax.swing.JLabel name1;
    private javax.swing.JComboBox<String> procede;
    private javax.swing.JComboBox<String> satisfaccion;
    private javax.swing.JLabel satisfaccion1;
    // End of variables declaration//GEN-END:variables
 



}
