/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import GestionDeQuejas.APP;
import GestionDeQuejas.Queja;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WINDOWS
 */
public class EliminarQ extends javax.swing.JFrame{
    int contCodigo;
private APP app;
DefaultTableModel dtm;
private Queja queja1;
    /**
     * Creates new form EliminarQ
     * @param app
     */
    public EliminarQ(APP app) {
        initComponents();
        this.app=app;
        setTitle("Eliminar Quejas");
       setLocationRelativeTo(null);
        contCodigo=0;
         dtm = (DefaultTableModel) View.jTable1.getModel();
         eliminar.setVisible(true);
      
         
    }

    private EliminarQ() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        introduzca = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        numq = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(304, 165));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(304, 165));
        jPanel1.setMinimumSize(new java.awt.Dimension(304, 165));
        jPanel1.setPreferredSize(new java.awt.Dimension(304, 165));

        introduzca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        introduzca.setForeground(new java.awt.Color(0, 102, 102));
        introduzca.setText("Introduzca el número de la queja:");

        eliminar.setBackground(new java.awt.Color(255, 255, 255));
        eliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/newpackage/True Eliminar.png"))); // NOI18N
        eliminar.setBorder(null);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        numq.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numqActionPerformed(evt);
            }
        });
        numq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numqKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(introduzca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numq, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(eliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(introduzca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numqKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (c < '0' || c > '9'||contCodigo >11)
        evt.consume();
        else{

            contCodigo ++;
        }
    }//GEN-LAST:event_numqKeyTyped

    private void numqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numqActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
         Registro p=new Registro();
         APP m=new APP();
        int j=Integer.parseInt(numq.getText());
        
          if(View.indicador==2 && j>101){
         j=m.getCant()%100;
          
         if (j==0){
             j=100;
       
         }else j=j-1;
        p.CambiardePagina(j);
       }
       if(View.indicador==3 && j>201 ){
         j=m.getCant()%100;
        
         if (j==0){
             j=100;
           
         }else j=j-1;
           p.CambiardePagina(j);
         
       }
       
         if(View.indicador==4 && j>301 ){
         j=m.getCant()%100;
        
         if (j==0){
             j=100;
           
         }else j=j-1;
         
         p.CambiardePagina(j);  
       }
         if(View.indicador==1 && j<100){
             j--;
              p.CambiardePagina(j);
         }
        app.delete(j-1);

        
        numq.setVisible(true);
        introduzca.setVisible(true);
        eliminar.setVisible(false);
       
        //        try {
            //        //        queja1.editDatos(p,nombre);
            ////        app.eliminarTodo();
            ////    } catch (SQLException ex) {
            ////        Logger.getLogger(EditQueja.class.getName()).log(Level.SEVERE, null, ex);
            ////    }
        ////
        ////        for (int i = 0; i < app.getCant(); i++) {
            ////            queja1.insertDatos(app.getQueja(i));
            ////
            ////        } 

        app.setCant(app.getCant()-1);
       
    }//GEN-LAST:event_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarQ().setVisible(true);
            }
        });
    }
   public void Color(int a){
        if(a==1){
    jPanel1.setBackground(Color.BLACK);
    eliminar.setBackground(Color.BLACK);
    eliminar.setBackground(Color.BLACK);
    numq.setBackground(Color.GRAY);
    introduzca.setForeground(Color.WHITE);
    eliminar.setForeground(Color.WHITE);
    eliminar.setForeground(Color.WHITE);}
        if(a==0){
        jPanel1.setBackground(Color.WHITE);
    eliminar.setBackground(Color.WHITE);
    eliminar.setBackground(Color.WHITE);
    numq.setBackground(Color.WHITE);
    introduzca.setForeground(Color.BLACK);
    eliminar.setForeground(Color.BLACK);
    eliminar.setForeground(Color.BLACK);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel introduzca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numq;
    // End of variables declaration//GEN-END:variables
}
