/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import GestionDeQuejas.APP;
import GestionDeQuejas.Queja;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import Visual.View;
import java.awt.Color;
import static java.awt.Color.red;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.util.Calendar;
import static java.util.Calendar.MONTH;

import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicArrowButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WINDOWS
 */
public class Registro extends javax.swing.JFrame {
private APP app;
DefaultTableModel dtm;

private Queja queja;
    /**
     * Creates new form Registro
     */
    public Registro(APP app) {
        initComponents();
        this.app=app;
        setTitle("Agregar Queja");
        dtm = (DefaultTableModel) View.jTable1.getModel();
        satisfaccion.setVisible(false);
        conclus_a.setVisible(false);
            conclus_b.setVisible(false);
            conclus_c.setVisible(false);
            satisfaccion1.setVisible(false);
            jLabel9.setVisible(false);
            respuesta.setVisible(false);
   
       
            
            
            
        
    }

    Registro() {
           initComponents();
        this.app=app;
        setTitle("Agregar Queja");
        dtm = (DefaultTableModel) View.jTable1.getModel();
        satisfaccion.setVisible(false);
        conclus_a.setVisible(false);
            conclus_b.setVisible(false);
            conclus_c.setVisible(false);
            satisfaccion1.setVisible(false);
            jLabel9.setVisible(false);
            respuesta.setVisible(false);

    }
    public void CambiardePagina(int j){
        APP m=new APP();
          dtm.setValueAt(m.getQueja(m.getCant()-1).getNombre(),j ,1); 
           dtm.setValueAt(m.getQueja(m.getCant()-1).getEntAfectada(),j,2);
           dtm.setValueAt(m.getQueja(m.getCant()-1).getModalidad(),j,3);
            dtm.setValueAt(m.getQueja(m.getCant()-1).getVia(),j,4);
             dtm.setValueAt(m.getQueja(m.getCant()-1).getProcedencia(),j,5);
              dtm.setValueAt(m.getQueja(m.getCant()-1).getClasificacion(),j,6);
               dtm.setValueAt(m.getQueja(m.getCant()-1).getCasoPrensa(),j,7);
                dtm.setValueAt(m.getQueja(m.getCant()-1).getConclusion(),j,8);
                dtm.setValueAt(m.getQueja(m.getCant()-1).getSatifaccion(),j,9);
                dtm.setValueAt(m.getQueja(m.getCant()-1).getSatisfaccion2(),j,10);
                 dtm.setValueAt(m.getQueja(m.getCant()-1).getFechaR(),j,11);
                  dtm.setValueAt(m.getQueja(m.getCant()-1).getFechaT(),j,12);
                  dtm.setValueAt(m.getQueja(m.getCant()-1).getFechaDeEntregaAlDepartamentoAfectado(),j,13);
                  dtm.setValueAt(m.getQueja(m.getCant()-1).getFechtaDeEntregaDeLaRespuesta(),j,14);
             
          name.setText(null);
    }
    public void buscar(String[]x){
       
        dtm.addRow(x);
    
            
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jMonthChooser2 = new com.toedter.calendar.JMonthChooser();
        jPanel1 = new javax.swing.JPanel();
        entrega = new javax.swing.JComboBox<>();
        procede = new javax.swing.JComboBox<>();
        entidad = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ADD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Vias = new javax.swing.JComboBox<>();
        Exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Conclusion = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        caso = new javax.swing.JComboBox<>();
        clasificacio = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        modalida = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        satisfaccion1 = new javax.swing.JLabel();
        recibo = new com.toedter.calendar.JDateChooser();
        satisfaccion = new javax.swing.JComboBox<>();
        termino = new com.toedter.calendar.JDateChooser();
        conclus_a = new javax.swing.JComboBox<>();
        departamento = new com.toedter.calendar.JDateChooser();
        conclus_b = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        conclus_c = new javax.swing.JComboBox<>();
        respuesta = new com.toedter.calendar.JDateChooser();
        entidad1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(435, 670));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(435, 670));
        jPanel1.setMinimumSize(new java.awt.Dimension(435, 670));
        jPanel1.setPreferredSize(new java.awt.Dimension(435, 670));

        entrega.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        entrega.setForeground(new java.awt.Color(102, 0, 0));
        entrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "Entregado", "No Entregado" }));
        entrega.setBorder(null);
        entrega.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        entrega.setFocusable(false);
        entrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregaActionPerformed(evt);
            }
        });

        procede.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        procede.setForeground(new java.awt.Color(102, 0, 0));
        procede.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "1. MINSAP", "2. PCC", "3. APPP", "4. Directo al Sectorial", "5. Otros" }));
        procede.setBorder(null);
        procede.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        procede.setFocusable(false);
        procede.setOpaque(false);
        procede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procedeActionPerformed(evt);
            }
        });

        entidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        entidad.setForeground(new java.awt.Color(102, 0, 0));
        entidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ", "1.Recursos Humanos", "2. Higiene y Epidemiología", "3. Asistencia Médica", "4. Vicedirección Económica", "5. Vicedirección General" }));
        entidad.setBorder(null);
        entidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        entidad.setFocusable(false);
        entidad.setOpaque(false);
        entidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entidadActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Clasificación:");

        ADD.setBackground(new java.awt.Color(255, 255, 255));
        ADD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ADD.setForeground(new java.awt.Color(0, 0, 51));
        ADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/newpackage/True Agregar.png"))); // NOI18N
        ADD.setBorder(null);
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Vías:");

        Vias.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Vias.setForeground(new java.awt.Color(102, 0, 0));
        Vias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "1. Carta", "2. Entrevista", "3. Teléfono" }));
        Vias.setBorder(null);
        Vias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Vias.setFocusable(false);
        Vias.setOpaque(false);

        Exit.setBackground(new java.awt.Color(255, 255, 255));
        Exit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(0, 0, 51));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/newpackage/Rectángulo 3.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Modalidad:");

        Conclusion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Conclusion.setForeground(new java.awt.Color(0, 0, 51));
        Conclusion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/newpackage/True Conclusiones.png"))); // NOI18N

        name.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 51, 102)));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Caso de prensa:");

        name1.setBackground(new java.awt.Color(255, 255, 255));
        name1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        name1.setForeground(new java.awt.Color(0, 102, 153));
        name1.setText("Nombre y Apellidos:");

        caso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        caso.setForeground(new java.awt.Color(102, 0, 0));
        caso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ", "No", "Plataforma Bienestar", "Periódico Granma" }));
        caso.setBorder(null);
        caso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        caso.setFocusable(false);
        caso.setMinimumSize(new java.awt.Dimension(226, 23));
        caso.setOpaque(false);
        caso.setPreferredSize(new java.awt.Dimension(226, 23));
        caso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casoActionPerformed(evt);
            }
        });

        clasificacio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        clasificacio.setForeground(new java.awt.Color(102, 0, 0));
        clasificacio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "1. Asistencia Médica", "2. APS y Enfermería", "3. Por fallecimiento", "4. Higiene", "5. Medicina óptica y audición", "6. Asistencia Social", "7. Docencia", "8. Laborales", "9. Problemas Administrativos", "10. Ambulancias", "11. Solicitud de RH y Materiales", "12. Construcción y Mantenimiento", "13. Trato", "14. Condiciones de trabajo", "15. Vivienda", "16. Salidas del pais ", "17. Otras", " " }));
        clasificacio.setBorder(null);
        clasificacio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clasificacio.setFocusable(false);
        clasificacio.setMinimumSize(new java.awt.Dimension(226, 23));
        clasificacio.setOpaque(false);
        clasificacio.setPreferredSize(new java.awt.Dimension(226, 23));
        clasificacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasificacioActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("Fecha Recibo:");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        modalida.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        modalida.setForeground(new java.awt.Color(102, 0, 0));
        modalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "1. Solicitud", "2. Queja", "3. Anónimo o Denuncia", "4. Sugerencia", "5. Reclamaciones", "6. Reconocimientos" }));
        modalida.setBorder(null);
        modalida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modalida.setFocusable(false);
        modalida.setOpaque(false);
        modalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modalidaActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setText("Fecha Término:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Procedencia:");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("Fecha Entrega Dpto Afectado:");

        satisfaccion1.setBackground(new java.awt.Color(255, 255, 255));
        satisfaccion1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        satisfaccion1.setForeground(new java.awt.Color(0, 102, 153));
        satisfaccion1.setText("Satisfacción:");

        recibo.setBackground(new java.awt.Color(255, 255, 255));
        recibo.setForeground(new java.awt.Color(0, 0, 51));
        recibo.setDateFormatString("yyyy-MM-dd");
        recibo.setIcon(null);
        recibo.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                reciboComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                reciboComponentRemoved(evt);
            }
        });
        recibo.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                reciboHierarchyChanged(evt);
            }
        });
        recibo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                reciboAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                reciboAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                reciboAncestorRemoved(evt);
            }
        });
        recibo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                reciboMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                reciboMouseMoved(evt);
            }
        });
        recibo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reciboFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                reciboFocusLost(evt);
            }
        });
        recibo.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                reciboMouseWheelMoved(evt);
            }
        });
        recibo.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                reciboAncestorMoved1(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                reciboAncestorResized(evt);
            }
        });
        recibo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reciboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reciboMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reciboMouseExited(evt);
            }
        });
        recibo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                reciboComponentHidden(evt);
            }
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                reciboComponentMoved(evt);
            }
        });
        recibo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                reciboCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                reciboInputMethodTextChanged(evt);
            }
        });
        recibo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                reciboPropertyChange(evt);
            }
        });
        recibo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reciboKeyPressed(evt);
            }
        });
        recibo.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                reciboVetoableChange(evt);
            }
        });

        satisfaccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        satisfaccion.setForeground(new java.awt.Color(102, 0, 0));
        satisfaccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "Conforme", "Conforme en Parte", "Inconforme" }));
        satisfaccion.setBorder(null);
        satisfaccion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        satisfaccion.setFocusable(false);
        satisfaccion.setMaximumSize(new java.awt.Dimension(135, 20));
        satisfaccion.setMinimumSize(new java.awt.Dimension(135, 20));
        satisfaccion.setOpaque(false);
        satisfaccion.setPreferredSize(new java.awt.Dimension(135, 25));
        satisfaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satisfaccionActionPerformed(evt);
            }
        });

        termino.setBackground(new java.awt.Color(255, 255, 255));
        termino.setForeground(new java.awt.Color(0, 0, 51));
        termino.setDateFormatString("yyyy-MM-dd");
        termino.setIcon(null);

        conclus_a.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        conclus_a.setForeground(new java.awt.Color(102, 0, 0));
        conclus_a.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ", "Con Razón", "Sin Razón", "Con Razón en Parte" }));
        conclus_a.setBorder(null);
        conclus_a.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        conclus_a.setFocusable(false);
        conclus_a.setMaximumSize(new java.awt.Dimension(135, 20));
        conclus_a.setOpaque(false);
        conclus_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conclus_aActionPerformed(evt);
            }
        });

        departamento.setBackground(new java.awt.Color(255, 255, 255));
        departamento.setForeground(new java.awt.Color(0, 0, 51));
        departamento.setDateFormatString("yyyy-MM-dd");
        departamento.setIcon(null);

        conclus_b.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        conclus_b.setForeground(new java.awt.Color(102, 0, 0));
        conclus_b.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "Resuelto", "En vías de solución", "Sin solución" }));
        conclus_b.setBorder(null);
        conclus_b.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        conclus_b.setFocusable(false);
        conclus_b.setMaximumSize(new java.awt.Dimension(135, 20));
        conclus_b.setMinimumSize(new java.awt.Dimension(135, 20));
        conclus_b.setOpaque(false);
        conclus_b.setPreferredSize(new java.awt.Dimension(135, 20));
        conclus_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conclus_bActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("Fecha Entrega de Respuesta:");

        conclus_c.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        conclus_c.setForeground(new java.awt.Color(102, 0, 0));
        conclus_c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "Con Lugar", "Con Lugar en Parte", "Sin Lugar" }));
        conclus_c.setBorder(null);
        conclus_c.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        conclus_c.setFocusable(false);
        conclus_c.setMaximumSize(new java.awt.Dimension(135, 20));
        conclus_c.setMinimumSize(new java.awt.Dimension(135, 20));
        conclus_c.setOpaque(false);
        conclus_c.setPreferredSize(new java.awt.Dimension(135, 20));
        conclus_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conclus_cActionPerformed(evt);
            }
        });

        respuesta.setBackground(new java.awt.Color(255, 255, 255));
        respuesta.setForeground(new java.awt.Color(0, 0, 51));
        respuesta.setDateFormatString("yyyy-MM-dd");
        respuesta.setIcon(null);

        entidad1.setBackground(new java.awt.Color(255, 255, 255));
        entidad1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        entidad1.setForeground(new java.awt.Color(0, 102, 153));
        entidad1.setText("Entidad Afectada:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Conclusion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(recibo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(termino, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(caso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clasificacio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(conclus_a, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name1)
                            .addComponent(satisfaccion1)
                            .addComponent(entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(satisfaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(entidad1)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entidad, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Vias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(modalida, 0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(procede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(name)
                            .addComponent(conclus_c, 0, 0, Short.MAX_VALUE)
                            .addComponent(conclus_b, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(name1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entidad1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(procede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(clasificacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(caso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Conclusion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(satisfaccion1)
                .addGap(7, 7, 7)
                .addComponent(satisfaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conclus_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conclus_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conclus_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(recibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(termino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ADD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregaActionPerformed
        int item = entrega.getSelectedIndex();
        int mod = modalida.getSelectedIndex();
        if (item==1) {
            satisfaccion.setVisible(true);
            satisfaccion1.setVisible(true);
        }
        if (item==2 || item==0){
            satisfaccion.setVisible(false);
            satisfaccion1.setVisible(false);
            conclus_a.setVisible(false);
            conclus_b.setVisible(false);
            conclus_c.setVisible(false);
             conclus_a.setSelectedIndex(0);
              conclus_b.setSelectedIndex(0);
               conclus_c.setSelectedIndex(0);
                satisfaccion.setSelectedIndex(0);
             

        }

        if(mod==0 && item==2 || mod==0 && item==0){
            conclus_a.setVisible(false);
            conclus_b.setVisible(false);
            conclus_c.setVisible(false);
             conclus_a.setSelectedIndex(0);
              conclus_b.setSelectedIndex(0);
               conclus_c.setSelectedIndex(0);
        }
        if(mod==1 && item==1){
            conclus_a.setVisible(false);
            conclus_b.setVisible(true);
            conclus_c.setVisible(false);
             conclus_a.setSelectedIndex(0);
              conclus_c.setSelectedIndex(0);
        }
        if(mod==2&& item==1){
            conclus_a.setVisible(true);
            conclus_b.setVisible(false);
            conclus_c.setVisible(false);
             conclus_b.setSelectedIndex(0);
              conclus_c.setSelectedIndex(0);
             
        }
        if(mod==3&& item==1){
            conclus_a.setVisible(false);
            conclus_b.setVisible(false);
            conclus_c.setVisible(true);
             conclus_a.setSelectedIndex(0);
              conclus_b.setSelectedIndex(0);
        }
        if(mod==4&& item==2 || mod==0 && item==0){
            conclus_a.setVisible(false);
            conclus_b.setVisible(false);
            conclus_c.setVisible(false);
             conclus_a.setSelectedIndex(0);
              conclus_b.setSelectedIndex(0);
               conclus_c.setSelectedIndex(0);
        }
        if(mod==5&& item==1){
            conclus_a.setVisible(false);
            conclus_b.setVisible(false);
            conclus_c.setVisible(true);
             conclus_a.setSelectedIndex(0);
              conclus_b.setSelectedIndex(0);
             
        }
        if(mod==6&& item==2 || mod==0 && item==0){
            conclus_a.setVisible(false);
            conclus_b.setVisible(false);
            conclus_c.setVisible(false);
             conclus_a.setSelectedIndex(0);
              conclus_b.setSelectedIndex(0);
               conclus_c.setSelectedIndex(0);
        }
        if (item==2||item==0){
            respuesta.setVisible(false);
            jLabel9.setVisible(false);
           
        }
        if (item==1){
            respuesta.setVisible(true);
            jLabel9.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_entregaActionPerformed

    private void procedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procedeActionPerformed

    private void entidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entidadActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed

        //Recoger datos//

        String nombre=name.getText();
        String entAfectada= entidad.getSelectedItem().toString();
        String modalidad=modalida.getSelectedItem().toString();
        String via=Vias.getSelectedItem().toString();
        String procedencia=procede.getSelectedItem().toString();
        String clasificacion=clasificacio.getSelectedItem().toString();
        String casoPrensa=caso.getSelectedItem().toString();
        
      

        // Condicion para a
       String satis2=null;
        String satis;
        int a1=conclus_a.getSelectedIndex();
         if (a1==1){
             satis2="Con Razón";
         }
         if (a1==2){
             satis2="Sin Razón";
         }
         if (a1==3){
             satis2="Con Razón en Parte";
         }
         //Condicion para b
          int b1=conclus_b.getSelectedIndex();
         if (b1==1){
             satis2="Resuelto";
         }
         if (b1==2){
             satis2="En vias de solución";
         }
         if (b1==3){
             satis2="Sin solución";
         }
         //Condicion para c
          int c1=conclus_c.getSelectedIndex();
         if (c1==1){
             satis2="Con Lugar";
         }
         if (c1==2){
             satis2="Con Lugar en Parte";
         }
         if (c1==3){
             satis2="Sin Lugar ";
         }
         
         //Condicion para satis
          satis=satisfaccion.getSelectedItem().toString();
        
      String fechaR=((JTextField)recibo.getDateEditor().getUiComponent()).getText();
      String fechaT=((JTextField)termino.getDateEditor().getUiComponent()).getText();
      String fechaDeEntregaAlDepartamentoAfectado=((JTextField)departamento.getDateEditor().getUiComponent()).getText();
      String fechtaDeEntregaDeLaRespuesta=((JTextField)respuesta.getDateEditor().getUiComponent()).getText();
      String entregado=entrega.getSelectedItem().toString();
   
      Queja queja = new Queja(nombre,entAfectada,modalidad,via,procedencia,clasificacion,casoPrensa,fechaR,fechaT,fechaDeEntregaAlDepartamentoAfectado,fechtaDeEntregaDeLaRespuesta,entregado,satis,satis2);
 if (nombre.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Debe introducir Nombre y Apellidos del Demandante");

        }  else {
   
             app.add(queja);
    
            JOptionPane.showMessageDialog(null, "Queja Agregada exitosamente");
 }
        
//        System.out.println(app.getQueja(0).getNombre());
//        queja.insertDatos(queja);
      
          int j=app.getCant();
          
       if(View.indicador==2 && j>101){
         j=app.getCant()%100;
          
         if (j==0){
             j=100;
       
         }else j=j-1;
        CambiardePagina(j);
       }
       if(View.indicador==3 && j>201 ){
         j=app.getCant()%100;
        
         if (j==0){
             j=100;
           
         }else j=j-1;
           CambiardePagina(j);
         
       }
       
         if(View.indicador==4 && j>301 ){
         j=app.getCant()%100;
        
         if (j==0){
             j=100;
           
         }else j=j-1;
         
         CambiardePagina(j);  
       }
         if(View.indicador==1 && j<100){
             j--;
              CambiardePagina(j);
         }
          
            
            
            
             
          
    }//GEN-LAST:event_ADDActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
  
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = false;
        boolean minusculas = false;
        boolean espacio = false;

        mayusculas = key >= 63 && key <= 90;
        minusculas = key >= 95 && key <= 122;
        espacio = key == 32;

        if (!(minusculas || mayusculas || espacio))
        evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyTyped

    private void clasificacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasificacioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clasificacioActionPerformed

    private void modalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modalidaActionPerformed
        int item = modalida.getSelectedIndex();
        int con = entrega.getSelectedIndex();
        if(item==0 && con==2 || item==0 && con==0 || item==0){
            conclus_a.setVisible(false);
            conclus_b.setVisible(false);
            conclus_c.setVisible(false);
            conclus_a.setSelectedIndex(0);
             conclus_b.setSelectedIndex(0);
              conclus_c.setSelectedIndex(0);
        }
        if(item==1 && con==1){
            conclus_a.setVisible(false);
            conclus_b.setVisible(true);
            conclus_c.setVisible(false);
             conclus_a.setSelectedIndex(0);
              conclus_c.setSelectedIndex(0);
        }
        if(item==2&& con==1){
            conclus_a.setVisible(true);
            conclus_b.setVisible(false);
            conclus_c.setVisible(false);
             conclus_b.setSelectedIndex(0);
              conclus_c.setSelectedIndex(0);
        }
        if(item==3&& con==1){
            conclus_a.setVisible(false);
            conclus_b.setVisible(false);
            conclus_c.setVisible(true);
             conclus_a.setSelectedIndex(0);
              conclus_b.setSelectedIndex(0);
        }
        if(item==4&& con==2 || item==0 && con==0|| item==4){
            conclus_a.setVisible(false);
            conclus_b.setVisible(false);
            conclus_c.setVisible(false);
             conclus_a.setSelectedIndex(0);
              conclus_b.setSelectedIndex(0);
               conclus_c.setSelectedIndex(0);
        }
        if(item==5&& con==1){
            conclus_a.setVisible(false);
            conclus_b.setVisible(false);
            conclus_c.setVisible(true);
             conclus_a.setSelectedIndex(0);
              conclus_b.setSelectedIndex(0);
        }
        if(item==6&& con==2 || item==0 && con==0 || item==6){
            conclus_a.setVisible(false);
            conclus_b.setVisible(false);
            conclus_c.setVisible(false);
             conclus_a.setSelectedIndex(0);
              conclus_b.setSelectedIndex(0);
               conclus_c.setSelectedIndex(0);
        }
    }//GEN-LAST:event_modalidaActionPerformed

    private void satisfaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satisfaccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satisfaccionActionPerformed

    private void conclus_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conclus_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conclus_aActionPerformed

    private void conclus_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conclus_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conclus_bActionPerformed

    private void conclus_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conclus_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conclus_cActionPerformed

    private void casoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casoActionPerformed

    private void reciboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reciboMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_reciboMouseClicked

    private void reciboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reciboMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_reciboMouseEntered

    private void reciboAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_reciboAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_reciboAncestorAdded

    private void reciboAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_reciboAncestorMoved
      // TODO add your handling code here:
    }//GEN-LAST:event_reciboAncestorMoved

    private void reciboAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_reciboAncestorRemoved
       // TODO add your handling code here:
    }//GEN-LAST:event_reciboAncestorRemoved

    private void reciboComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_reciboComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_reciboComponentHidden

    private void reciboComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_reciboComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_reciboComponentMoved

    private void reciboComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_reciboComponentAdded
        // TODO add your handling code here:
      
    }//GEN-LAST:event_reciboComponentAdded

    private void reciboComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_reciboComponentRemoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_reciboComponentRemoved

    private void reciboMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reciboMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_reciboMouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        try{
          Calendar fecha=recibo.getCalendar();
 departamento.setCalendar(fecha);
      fecha.add(MONTH, 1);
      termino.setCalendar(fecha);
    
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void reciboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reciboKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_reciboKeyPressed

    private void reciboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reciboFocusGained
   try{
          Calendar fecha=recibo.getCalendar();
departamento.setCalendar(fecha);
      fecha.add(MONTH, 1);
      termino.setCalendar(fecha);
       
        }catch(Exception e){
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_reciboFocusGained

    private void reciboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reciboFocusLost
        // TODO add your handling code here:
           try{
          Calendar fecha=recibo.getCalendar();
 departamento.setCalendar(fecha);
      fecha.add(MONTH, 1);
      termino.setCalendar(fecha);
     
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_reciboFocusLost

    private void reciboHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_reciboHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_reciboHierarchyChanged

    private void reciboAncestorMoved1(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_reciboAncestorMoved1
        // TODO add your handling code here:
    }//GEN-LAST:event_reciboAncestorMoved1

    private void reciboAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_reciboAncestorResized
        // TODO add your handling code here:
    }//GEN-LAST:event_reciboAncestorResized

    private void reciboCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_reciboCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_reciboCaretPositionChanged

    private void reciboInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_reciboInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_reciboInputMethodTextChanged

    private void reciboMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reciboMouseDragged
        // TODO add your handling code here:
           try{
          Calendar fecha=recibo.getCalendar();
 departamento.setCalendar(fecha);
      fecha.add(MONTH, 1);
      termino.setCalendar(fecha);
       
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_reciboMouseDragged

    private void reciboMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reciboMouseMoved
        // TODO add your handling code here:
           try{
          Calendar fecha=recibo.getCalendar();
  departamento.setCalendar(fecha);
      fecha.add(MONTH, 1);
      termino.setCalendar(fecha);
         
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_reciboMouseMoved

    private void reciboMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_reciboMouseWheelMoved
        // TODO add your handling code here:
           try{
          Calendar fecha=recibo.getCalendar();
 departamento.setCalendar(fecha);
      fecha.add(MONTH, 1);
      termino.setCalendar(fecha);
     
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_reciboMouseWheelMoved

    private void reciboPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_reciboPropertyChange
        // TODO add your handling code here:
           try{
          Calendar fecha=recibo.getCalendar();
 departamento.setCalendar(fecha);
      fecha.add(MONTH, 1);
      termino.setCalendar(fecha);
       
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_reciboPropertyChange

    private void reciboVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_reciboVetoableChange
        // TODO add your handling code here:
           try{
          Calendar fecha=recibo.getCalendar();
 departamento.setCalendar(fecha);
      fecha.add(MONTH, 1);
      termino.setCalendar(fecha);
       
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_reciboVetoableChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JLabel Conclusion;
    private javax.swing.JButton Exit;
    private javax.swing.JComboBox<String> Vias;
    private javax.swing.JComboBox<String> caso;
    private javax.swing.JComboBox<String> clasificacio;
    private javax.swing.JComboBox<String> conclus_a;
    private javax.swing.JComboBox<String> conclus_b;
    private javax.swing.JComboBox<String> conclus_c;
    private com.toedter.calendar.JDateChooser departamento;
    private javax.swing.JComboBox<String> entidad;
    private javax.swing.JLabel entidad1;
    private javax.swing.JComboBox<String> entrega;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private com.toedter.calendar.JMonthChooser jMonthChooser2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> modalida;
    private javax.swing.JTextField name;
    private javax.swing.JLabel name1;
    private javax.swing.JComboBox<String> procede;
    private com.toedter.calendar.JDateChooser recibo;
    private com.toedter.calendar.JDateChooser respuesta;
    private javax.swing.JComboBox<String> satisfaccion;
    private javax.swing.JLabel satisfaccion1;
    private com.toedter.calendar.JDateChooser termino;
    // End of variables declaration//GEN-END:variables

            
 


}
